_BASE_: MinVIS_R50.yaml
MODEL:
  META_ARCHITECTURE: "CAVIS_segmenter"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoder_cavis"
    REID_BRANCH: True
    CONTEXT_FILTER_SIZE: 9

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 3
  SAMPLING_FRAME_RANGE: 2
