_BASE_: CAVIS_Segmenter_R50.yaml

MODEL:
  META_ARCHITECTURE: "CAVIS_online"
  TRACKER:
    USE_CL: False

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 2
