_BASE_: CAVIS_Online_R50.yaml

MODEL:
  META_ARCHITECTURE: "CAVIS_offline"

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (112000,)
  MAX_ITER: 160000

INPUT:
  SAMPLING_FRAME_NUM: 15
  SAMPLING_FRAME_RANGE: 7
  REVERSE_AGU: True